### ISSUE TITLE
No port specified in UDP Tracker

### ISSUE THREAD

**Issue by rajan22** [vaishious/has-torrent#10]

**Comment by vaishious** [comment]
Details? Bind to special aNY_PORT and iNADDR_ANY. This will generate a UDP port for us. Use the same port for TCP connections.

**Comment by rajan22** [comment]
What I was talking about was this. If some announce url in the announce list of the .torrent file does not specify the port of the tracker host, then what port should we store in the Tracker datatype for that tracker?

**Comment by vaishious** [comment]
80 for HTTP
443 for HTTPS

UDP must have a port. There exists a package for parsing these strings and extracting protocol and hostname, port in haskell. We'll use that I guess.

**Comment by rajan22** [comment]
Hmm. I'm currently using this library for parsing URLs. 
http://hackage.haskell.org/package/network-2.1.0.0/docs/Network-URI.html

**Comment by vaishious** [comment]
Perfect. This is the one I was talking about. (y)

**Comment by vaishious** [comment]
Finally. I don't think it's possible to have a standard port for UDP. It's a data transfer protocol. Not a data formatting protocol. A quick google search for UDP Tracker standard port gave no results. From wikipedia -> "URLs for this protocol have the following format: udp://tracker:port."

**Comment by vaishious** [comment]
Okay. It turns out that there were some torrent files without any port for UDP tracker.
For these Deluge sends a request on 443. But I haven't seen any replies. So it's just a placeholder (probably). Added 443 as a placeholder in Bencode.hs just for error handling and parser handling
